### ISSUE TITLE
Number of people who contributed any code in the last year 

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/annual-report-help#3]
### Goal i.e. What question do we need to answer

How many people contributed any code in the last year to rOpenSci packages in https://github.com/ropensci? (not including ropenscilabs)

A related question to this could be: How many people contributed any code to at least 2 pkgs? Or 3? etc. (clearly cont. any code to 1 pkg would be the biggest number though)

### What items do we need

* Github commits data, not all code contributors are listed in DESCRIPTION authors, so we'd need commits

### How to acquire these items

* Github commits data from the Github API for all pkgs of interest

**Comment by czeildi** [comment]
I'd like to tackle this.

**Comment by stefaniebutland** [comment]
I'm thrilled to hear this Ildi. Let us know if you need further info or have questions as you start. Thank you!

**Comment by czeildi** [comment]
I created a first version of the report.

Summary:
- I counted 312 code contributors between 2018-09-01 and 2019-09-01
- repo with source code (see [README](https://github.com/czeildi/gh-contributors/blob/master/README.md) for how to use) and results for period between 2018-09-01 and 2019-09-01: https://github.com/czeildi/gh-contributors
- report: https://github.com/czeildi/gh-contributors/blob/master/results/ropensci_2018-09-01_2019-09-01/code_contributors.md
- summary data in csv format: https://github.com/czeildi/gh-contributors/tree/master/results/ropensci_2018-09-01_2019-09-01
- I can easily generate the results for another period, I was not sure what `last year` means (you should be able to do this too following the [readme](https://github.com/czeildi/gh-contributors/blob/master/README.md#running))

Notes:
- For a small percentage of the commits the github API did not return author information for me in the form of github_login. I suspect this happens when someone commits with an unknown email address.  For most of these commits I could identify users based on commit author name.
  - For some commits no identifiable information was available. Thus it is possible that some contributors are missed. (4 such commits out of several thousand.)
  - There might be duplicates in the case of user identification based on name instead of github login. I checked manually so it should not be substantial even if it happens.
- One person might use multiple github users, I counted github users and did not attempt to count people  
- Based on eyeballing the data I excluded web-flow and ropenscibot commits as probably not relevant

### Preview of summary report:
### Authors by number of repositories they contributed to


|n_repo | n_author|
|:------|--------:|
|1      |      225|
|2      |       54|
|3      |       15|
|4      |        3|
|5      |        4|
|6-10   |        6|
|11-50  |        3|
|50+    |        2|

### Authors by number of commits they made


|n_commit | n_author|
|:--------|--------:|
|1        |       84|
|2-5      |       78|
|6-10     |       37|
|11-100   |       72|
|101-1000 |       37|
|1000+    |        4|

**Comment by stefaniebutland** [comment]
Thank you @czeildi! We'll have a look and ask if we have any questions.

**Comment by sckott** [comment]
Thanks so so much @czeildi ! This is great. A few requests, apologies in advance for these:

- good idea on excluding bots!
- duplicates: would it be possible to collapse data for people with multiple user names? e.g., `wlandau` and `wlandau-lilly` ? maybe inspecting the commit data somehow, or a separate input file with known duplicates?
- package dependencies: is there a way to make package dependencies more explicit? i know this is script based, and not a package, but at least documenting required pkgs in readme, etc.
- ideally, we'd only consider here R packages, and only those in our registry, could you first limit the repos requested, or filter afterwards?  You can use data from our registry in https://raw.githubusercontent.com/ropensci/roregistry/gh-pages/registry.json and filter to those repos with `github.com/ropensci/` in their `url` field, rather than `github.com/ropenscilabs/`
- Would it be easy enough to show a table of new contributors in the last year?

i tried running the code:

- with `01_collect_contributors.R`, since there's caching involved, could you mention at least briefly that the data will be pulled from locally cached data if available, and that if you want new data to delete those files (or whatever you suggest doing)

**Comment by czeildi** [comment]
The results are here: https://github.com/czeildi/ghcontributors/tree/master/results/ropensci_2018-09-01_2019-09-01 (Note that I renamed the repo so that it can be a package easily.)

> * duplicates: would it be possible to collapse data for people with multiple user names? e.g., `wlandau` and `wlandau-lilly` ? maybe inspecting the commit data somehow, or a separate input file with known duplicates?

Sure, I included a [yml](https://github.com/czeildi/ghcontributors/blob/master/scripts/people_w_multiple_gh_users.yml) and a report which suggests what to put into the yml based on same name or email. I kept this as manual because for example 2 people might have the same name (Andrew) but they are actually 2 people so I do not see a way to fully automate this.

> * package dependencies: is there a way to make package dependencies more explicit? i know this is script based, and not a package, but at least documenting required pkgs in readme, etc.

Sure, I converted the repo to a package with a DESCRIPTION file. I am not sure what is the standard, currently you should still run the scripts in developer mode (i.e. no package install is supposed to happen.) `devtools::install_dev_deps()` and `devtools::load_all()` should take care of everything you need to run the scripts.

> * ideally, we'd only consider here R packages, and only those in our registry, could you first limit the repos requested, or filter afterwards?  You can use data from our registry in https://raw.githubusercontent.com/ropensci/roregistry/gh-pages/registry.json and filter to those repos with `github.com/ropensci/` in their `url` field, rather than `github.com/ropenscilabs/`

Sure, I filtered for repositories under `ropensci` which are in the registry as well

> * Would it be easy enough to show a table of new contributors in the last year?

Sure, included. However, for this I collected all-time commit history so data collection from the GitHub API now takes longer.

> i tried running the code:
> 
> * with `01_collect_contributors.R`, since there's caching involved, could you mention at least briefly that the data will be pulled from locally cached data if available, and that if you want new data to delete those files (or whatever you suggest doing)

Great idea, added to the readme. 

Let me know if you have further questions, requests or ideas.

**Comment by sckott** [comment]
thanks very much @czeildi ! LGTM

**Comment by stefaniebutland** [comment]
Thank you @czeildi !!!

**Comment by stefaniebutland** [comment]
@czeildi Thank you so much for contributing this solution! We’ll use your code in making our reports. Do you consent to us publicly acknowledging you for this (e.g. in a report)?

**Comment by czeildi** [comment]
Sure. Glad to be of help.
