### ISSUE TITLE
Number of authors per package

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/annual-report-help#4]
### Goal i.e. What question do we need to answer

Does the number of maintainers per package change through time?

In the interest of software sustainability, ideally each package would have more than one maintainer, but this is relatively rare. We'd like to see the number of maintainers per package increase over time, but number of maintainers is hard to address without detailed knowledge of each repo. As a proxy, we could count up all authors regardless of their role (not counting reviewers, funders). 

Question becomes: Does the number of authors per package change (increase) through time?

### What items do we need

- Data set of packages with author names through time and code to produce this

### How to acquire these items

1. Github API, just `DESCRIPTION` file changes through time - OR - could use authors section in current + archived versions of packages on CRAN (but that only includes pkgs on CRAN, and only history as far back as first ver. on CRAN)

**Comment by elinw** [comment]
Are you talking about authors as listed in the DESCRIPTION file?

**Comment by stefaniebutland** [comment]
Yes. @sckott might have a further comment

**Comment by sckott** [comment]
Well, I think we'd prefer to have the sort of main maintainers that share leadership role in a package, but I don't think there's a way to get that information programatically. 

So as a proxy I think we can just use authors in DESCRIPTION files. I imagine folks don't use the roles consistently (i.e,. `aut` vs. `ctb`, etc) - if they did we could look at number of `aut` assuming those are the maintainers. Would be interesting to look at roles nonetheless

**Comment by patperu** [comment]
Maybe this could be a first start https://gist.github.com/patperu/c578d78530e9d1d2900b6b9304ca8800
The package [desc](https://github.com/r-lib/desc) could be very helpful.

**Comment by mpadge** [comment]
You could also analyse/compare/contrast numbers of git commits (or even lines of code) to get a more quantitative insight into authorial contributions.

**Comment by sckott** [comment]
thanks @patperu - can you describe what the script is doing in words?

good idea @mpadge - do you want to experiment with that a bit?

**Comment by mpadge** [comment]
I'd love to @sckott, but am very time-constrained at present. I will endeavour to find some time hopefully by early next week at the latest.

**Comment by sckott** [comment]
thanks @mpadge

**Comment by patperu** [comment]
Hi @sckott, I'll do it tomorrow.

**Comment by mpadge** [comment]
@sckott sometimes the best policy really is just to wait ... now @czeildi has gone and done most of the work for this anyway. The only remaining task is to align the [`ghcontributors`](https://github.com/czeildi/ghcontributors) output with authors as listed in DESCRIPTION files, and we'll be done. Thanks @czeildi - great work!

**Comment by sckott** [comment]
@mpadge right, makes sense

**Comment by sckott** [comment]
did some stuff using and building on Ildikó's code: 

```r
library(lubridate)
library(ggplot2)
authors_month <- cleaned_commits %>%
  group_by(repo, month=floor_date(commit_date, "month")) %>%
  summarize(n_author = length(unique(author_login))) %>% 
  ungroup()
```

But thought maybe its better to just use description file info from each cran version:

```r
library(crandb)
library(jsonlite)
library(dplyr)
x <- fromJSON("https://raw.githubusercontent.com/ropensci/roregistry/gh-pages/registry.json")
pkg_names <- filter(x$packages, on_cran) %>% .$name
res <- lapply(pkg_names, function(w) {
  pkg <- package(w, version = "all")
  counts <- vapply(pkg$versions, function(z) {
    if (is.null(z$`Authors@R`)) {
      length(strsplit(z$`Author`, ",")[[1]])
    } else {
      auts <- eval(parse(text = gsub("<U\\+000a>", "", z$`Authors@R`)))
      length(auts[!grepl("\\[rev\\]|\\[cph\\]|\\[fnd\\]", auts)])
    }
  }, 1)
  dates <- vapply(pkg$versions, function(z) z$Date, "")
  tibble(name = w, n_authors = counts, dates = dates)
})
df <- dplyr::bind_rows(res)
# in past year, how many new authors were added
filter(df, dates > as.Date("2018-09-01")) %>% 
  group_by(name) %>% 
  summarize(change = max(n_authors) - min(n_authors)) %>% 
  arrange(desc(change)) %>% head() %>% knitr::kable()
```

|name           | change|
|:--------------|------:|
|drake          |      4|
|skimr          |      3|
|landscapetools |      2|
|rnassqs        |      2|
|tidync         |      2|
|bomrang        |      1|

**Comment by mpadge** [comment]
@sckott I've got the basic infrastructure set up in [this repo](https://github.com/mpadge/ros-pkg-authors). Currently just aggregates everything regardless of time, and returns results like this:


<table>
<thead>
<tr class="header">
<th style="text-align: left;">repo</th>
<th style="text-align: right;">nauthors</th>
<th style="text-align: right;">pc_official_commits</th>
<th style="text-align: right;">pc_official_lines</th>
<th style="text-align: right;">pc_author1_commits</th>
<th style="text-align: right;">pc_author1_lines</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">auk</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: commitsright;">1.0000000</td>
<td style="text-align: right;">1.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">available</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.8238095</td>
<td style="text-align: right;">0.8671949</td>
<td style="text-align: right;">0.5952381</td>
<td style="text-align: right;">0.4748019</td>
</tr>
<tr class="odd">
<td style="text-align: left;">conditionz</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">1.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">eechidna</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.5132275</td>
<td style="text-align: right;">0.9678170</td>
<td style="text-align: right;">0.3333333</td>
<td style="text-align: right;">0.0170128</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rcitoid</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">1.0000000</td>
<td style="text-align: right;">1.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">vitae</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.7155556</td>
<td style="text-align: right;">0.9155717</td>
<td style="text-align: right;">0.7155556</td>
<td style="text-align: right;">0.9155717</td>
</tr>
</tbody>
</table>

The stats are currently:
1. `pc_official_commits` proportion of commits by "official" authors listed in DESC file
2. `pc_official_lines` proportion of lines of code by "official" authors listed in DESC file
3. `pc_author1_commits` proportion of commits by primary git contributor
4. `pc_author1_lines` proportions of lines of code by primary git contributor

"official" in all cases refers to people listed in a DESCRIPTION file.

I know this is not really what you want, but my Q is how these kinds of analyses can now be modified to answer your question. It essentially just involves intermediate steps of `group_by(...)` to sub-select chunks of time, and then doing final analysis on temporal trends (i guess?). Annual chunks seem obviously the best, but that generally yields so few years that no real statistics can come out of it. On the other hand, monthly chunks can be extremely noisy, and so potentially also not optimal. Maybe quarterly?

How would it be to do your number of author analysis from `crandb` stuff, and calculate rates of change over time, along with equivalent rates of change (on a quarterly basis, as per the above), in:
1. numbers of distinct yet official contributors; and
2. numbers of contributions (both commits and lines of code) from non-primary yet official (as per DESC) authors?

These *may* reveal some kind of consistent temporal patterns ... ?

---

Edit: The thing to keep in mind, I would suggest, would be the fundamental difference between the 2 kinds of data. "Official" authorship is in effect cumulative, because there is generally no going back once a new author has been added to a DESC file. That reflects the extent to which a community contributes to a singular "thing". In contrast, repo stats are reflect the extent to which a community contributes to the ongoing life of that "thing", rather than just the aggregate or cumulative contribution. Is software a static entity, or a product of living community enterprise? No answer of course, but these two kinds of data reflect those two sides of the coin.

**Comment by sckott** [comment]
Thanks for this @mpadge !

Quarterly seems like a good time step

Your 1 and 2 both sound good to me. Are you offering to do those?

> Is software a static entity, or a product of living community enterprise?

good question!  i'd definitely lean towards **living** - at least in terms of the health of a software project, contributors that used to contribute but no longer do are no longer helping, so even if 10 authors are listed e.g., I guess what matters is how many contributors could actually contribute now-ish?

**Comment by mpadge** [comment]
here we go ...

![out](https://user-images.githubusercontent.com/6697851/65724978-e3f79e80-e0b1-11e9-8930-ba4a462882b4.png)

those are histograms of rates of linear change over time in (commits from other than non-primary maintainers, numbers of contributors, lines of code from other than non-primary maintainer). The ~~latter two~~first and third are proportions relative to overall (commits / lines) for each (quarterly) time period.

- **number of commits** - significant increase over time - :rocket: :tada: 
- **number of contributors** - no significant change at all
- **number of lines of code** - non-significant increase, seemingly due to the fact the primary maintainers commit the overwhelming majority of code regardless.

So the result you wanted emerges from an overall statistically significant increase (t = 2.6848, df = 195, p-value = 0.007881) in the proportions of commits per unit time from people other than non-primary maintainers. I'll commit the associated code and results tomorrow (it's late evening for me now). Is it best to do that in the repo i made? or somewhere else?

### provisional conclusion

A piece of software is indeed a living, evolving thing representing processes of community growth, and not simply a static aggregation of prior effort.

**Comment by sckott** [comment]
neat stuff. Yeah, put in your repo.

**Comment by mpadge** [comment]
... of course, this does not exactly meet your initial request, because it would appear that there is no significant change in numbers of authors per package over time (other than perhaps increases expected due to accumulation on DESC files), but it offers a pretty satisfactory alternative that still demonstrates what I think/hope you wanted, namely that broader community engagement in the code of packages increases over time according to at least one metric. Easy enuff to modify the code if you can think of any alternative analytic approaches - just let me know.

**Comment by mpadge** [comment]
@sckott This was all quite a bit tricker than anticipated. I think I now have one definitive answer, as detailed at length in [the repo](https://github.com/mpadge/ros-pkg-authors). What I did was to quantify the relative contributions of non-primary contributors in decreasing order, and measures the slopes with increasing numbers of contributors. Those slopes will always be negative (or zero). Increases in numbers of additional non-primary contributors will generally make those slopes less negative. Importantly, increases in the relative contributions of additional contributors will also make them less negative, independent of any increases in actual numbers of contributors. I consider both of these to be equivalent - equivalent to presuming "more people participating" being equivalent to "people participating more often".

Given that, my final result that i can offer you for the moment is this:
![authors-per-time-interval-1](https://user-images.githubusercontent.com/6697851/65879623-7e94fd80-e390-11e9-858f-22bc503c3f90.png)

These show changes in the slopes of relative changes over time in (commits/lines of code) with increasing numbers of contributors. Changes in relative numbers of commits (left-hand panel) do indeed become significantly less negative over time, indicating relatively greater contributions from greater numbers of contributors. Equivalent changes in numbers of lines of code (right-hand panel) are not significant.

That's all I can do for now - hope it helps.

**Comment by sckott** [comment]
This is great, thanks so much Mark. 

We won't be able to include much more than a few summary values to demonstrate a point in our report, but if you're interested, might be fun to explore this a bit more in a blog post on our blog. or your own if you have one.

**Comment by stefaniebutland** [comment]
@mpadge Thank you for being so generous with your extra work and thinking. We’ll use some of your code in making our reports. Do you consent to us publicly acknowledging you for this (e.g. in a report)?

**Comment by mpadge** [comment]
Absolutely and indeed. Feel free to use, abuse, and acknowledge any way you see fit. One Q but, extending from Scott's maybe suggestion: A blog piece on ROS blog? No worries if not, but it'll gain loads more readership than putting it on my blog

**Comment by stefaniebutland** [comment]
Yes rOpenSci blog. Ideally it would be a concise version of your analysis with a clear statement of the question you addressed and why it's important. Given the result it would be nice to have a "call to action" at the end.

Here are the guidelines, which have been updated since you last wrote one.
https://github.com/ropensci/roweb2#contributing-a-blog-post

Note that you have an author page https://ropensci.org/authors/mark-padgham/

Happy to answer any questions via Slack.

I'll close this issue now. Thank you Mark!
